// GENERATED by tools/convert-hershey.mjs — do not edit.
// The Hershey license requires these acknowledgements to be distributed WITH the
// font data — hence a string constant the face modules reference (a bundler can't
// drop it while a face is in use), not just a comment. Full terms: LICENSE-hershey.
/*! The Hershey Fonts were originally created by Dr. A. V. Hershey while working at the U. S. National Bureau of Standards. The format of the Font data in this distribution was originally created by James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821 (mit-eddie!ci-dandelion!hurt). */
export const HERSHEY_LICENSE =
	'The Hershey Fonts were originally created by Dr. A. V. Hershey while working at the U. S. National Bureau of Standards. The format of the Font data in this distribution was originally created by James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821 (mit-eddie!ci-dandelion!hurt).';
