// One-off converter: tools/jhf/*.jhf → src/faces/*.ts — the vendored Hershey
// stroke faces as packed pair strings. Run by hand (`node tools/convert-hershey.mjs`
// from packages/neon, then `yarn prettier --write src/faces` — the emitter quotes
// with JSON.stringify); the output is checked in, so the build never runs this —
// same policy as nixie's authored SVG glyphs. The .jhf sources are the classic
// Jeff Epler distribution (mirrored at github.com/kamalmostafa/hershey-fonts, the
// Debian upstream); their license rides along in tools/jhf/LICENSE.upstream and
// ships as the package's LICENSE-hershey.
//
// JHF, per glyph: cols 0–4 glyph id, cols 5–7 pair count, then `count` char pairs
// (charCode − 'R' per coordinate, y down). The FIRST pair is the left/right margin
// (advance = right − left); a ' R' pair (space + R) is pen-up. A glyph may wrap
// onto continuation lines — consume by pair count, not by line.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const R = 'R'.charCodeAt(0);

/** Parse one .jhf file into 95 packed glyph strings (raw pair chars, margins first). */
function parseJhf(file) {
	const lines = readFileSync(file, 'utf8').replace(/\r/g, '').split('\n');
	const glyphs = [];
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (!line.trim()) continue;
		const count = parseInt(line.slice(5, 8), 10);
		if (!Number.isFinite(count) || count < 1) throw new Error(`${file}: bad header at line ${i}`);
		let data = line.slice(8);
		while (data.length < count * 2) data += lines[++i]; // wrapped continuation lines
		glyphs.push(data.slice(0, count * 2));
	}
	// The classic files carry 96 glyphs, 0x20–0x7F — the last sits at the DEL
	// position (a cursor/degree filler, not printable ASCII). Keep the first 95.
	if (glyphs.length < 95)
		throw new Error(`${file}: expected ≥95 glyphs (ASCII 0x20–0x7E), got ${glyphs.length}`);
	return glyphs.slice(0, 95);
}

/** Decode one packed glyph to strokes in raw JHF units (for metrics only). */
function strokesOf(packed) {
	const strokes = [];
	let cur = null;
	for (let j = 2; j < packed.length; j += 2) {
		if (packed[j] === ' ' && packed[j + 1] === 'R') {
			cur = null;
			continue;
		}
		if (!cur) strokes.push((cur = []));
		cur.push([packed.charCodeAt(j) - R, packed.charCodeAt(j + 1) - R]);
	}
	return strokes;
}

/** Face metrics from the data itself (no magic constants): baseline and cap top
 *  from the flat-bottomed capitals — 'Q' tails and script swashes would poison a
 *  full A–Z sweep. Both classic faces land on the Hershey convention (9 / −12). */
function metrics(glyphs) {
	let baseline = -Infinity;
	let capTop = Infinity;
	for (const ch of 'HEITA') {
		for (const s of strokesOf(glyphs[ch.charCodeAt(0) - 32]))
			for (const [, y] of s) {
				baseline = Math.max(baseline, y);
				capTop = Math.min(capTop, y);
			}
	}
	let top = Infinity;
	let bottom = -Infinity;
	for (const g of glyphs)
		for (const s of strokesOf(g))
			for (const [, y] of s) {
				top = Math.min(top, y);
				bottom = Math.max(bottom, y);
			}
	return {
		baseline,
		capHeight: baseline - capTop,
		ascent: baseline - top,
		descent: bottom - baseline
	};
}

const ACK =
	'The Hershey Fonts were originally created by Dr. A. V. Hershey while working at ' +
	'the U. S. National Bureau of Standards. The format of the Font data in this ' +
	'distribution was originally created by James Hurt, Cognition, Inc., 900 ' +
	'Technology Park Drive, Billerica, MA 01821 (mit-eddie!ci-dandelion!hurt).';

function emitLicense() {
	const src = `// GENERATED by tools/convert-hershey.mjs — do not edit.
// The Hershey license requires these acknowledgements to be distributed WITH the
// font data — hence a string constant the face modules reference (a bundler can't
// drop it while a face is in use), not just a comment. Full terms: LICENSE-hershey.
/*! ${ACK} */
export const HERSHEY_LICENSE = ${JSON.stringify(ACK)};
`;
	writeFileSync(join(here, '../src/faces/hershey-license.ts'), src);
}

function emitFace(jhf, out, name, doc, grouping) {
	const glyphs = parseJhf(join(here, 'jhf', jhf));
	const m = metrics(glyphs);
	const rows = glyphs.map((g) => `\t\t${JSON.stringify(g)}`).join(',\n');
	const src = `// GENERATED by tools/convert-hershey.mjs from tools/jhf/${jhf} — do not edit.
// ${doc}
// 95 printable-ASCII glyphs as packed JHF pair strings (charCode − 82 per
// coordinate, y down; first pair = left/right margins; ' R' = pen up).
/*! ${ACK} */
import type { PackedFace } from '../font';
import { HERSHEY_LICENSE } from './hershey-license';

export const ${name}: PackedFace = {
	grouping: ${JSON.stringify(grouping)},
	baseline: ${m.baseline},
	capHeight: ${m.capHeight},
	ascent: ${m.ascent},
	descent: ${m.descent},
	license: HERSHEY_LICENSE,
	data: [
${rows}
	]
};
`;
	writeFileSync(join(here, '../src/faces', out), src);
	console.log(`${out}: 95 glyphs, ${JSON.stringify(m)}`);
}

emitLicense();
emitFace(
	'futural.jhf',
	'sans.ts',
	'SANS',
	"Hershey Simplex ('futural') — clean single-stroke sans; block-letter channel signs.",
	'glyph'
);
emitFace(
	'scripts.jhf',
	'script.ts',
	'SCRIPT',
	"Hershey Script simplex ('scripts') — connected cursive; the classic one-tube-per-word window sign.",
	'word'
);
